/*
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
 

namespace SpaceTradersDotNetSDK.Models
{
    /// <summary>
    /// The chart of a system or waypoint, which makes the location visible to other agents.
    /// </summary>
    [DataContract]
    public partial class Chart :  IEquatable<Chart>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Chart" /> class.
        /// </summary>
        /// <param name="waypointSymbol">waypointSymbol.</param>
        /// <param name="submittedBy">submittedBy.</param>
        /// <param name="submittedOn">submittedOn.</param>
        public Chart(string waypointSymbol = default(string), string submittedBy = default(string), DateTime submittedOn = default(DateTime))
        {
            this.WaypointSymbol = waypointSymbol;
            this.SubmittedBy = submittedBy;
            this.SubmittedOn = submittedOn;
        }

        /// <summary>
        /// Gets or Sets WaypointSymbol
        /// </summary>
        [DataMember(Name="waypointSymbol", EmitDefaultValue=false)]
        public string WaypointSymbol { get; set; }

        /// <summary>
        /// Gets or Sets SubmittedBy
        /// </summary>
        [DataMember(Name="submittedBy", EmitDefaultValue=false)]
        public string SubmittedBy { get; set; }

        /// <summary>
        /// Gets or Sets SubmittedOn
        /// </summary>
        [DataMember(Name="submittedOn", EmitDefaultValue=false)]
        public DateTime SubmittedOn { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Chart {\n");
            sb.Append("  WaypointSymbol: ").Append(WaypointSymbol).Append("\n");
            sb.Append("  SubmittedBy: ").Append(SubmittedBy).Append("\n");
            sb.Append("  SubmittedOn: ").Append(SubmittedOn).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Chart);
        }

        /// <summary>
        /// Returns true if Chart instances are equal
        /// </summary>
        /// <param name="input">Instance of Chart to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Chart input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.WaypointSymbol == input.WaypointSymbol ||
                    (this.WaypointSymbol != null &&
                    this.WaypointSymbol.Equals(input.WaypointSymbol))
                ) && 
                (
                    this.SubmittedBy == input.SubmittedBy ||
                    (this.SubmittedBy != null &&
                    this.SubmittedBy.Equals(input.SubmittedBy))
                ) && 
                (
                    this.SubmittedOn == input.SubmittedOn ||
                    (this.SubmittedOn != null &&
                    this.SubmittedOn.Equals(input.SubmittedOn))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.WaypointSymbol != null)
                    hashCode = hashCode * 59 + this.WaypointSymbol.GetHashCode();
                if (this.SubmittedBy != null)
                    hashCode = hashCode * 59 + this.SubmittedBy.GetHashCode();
                if (this.SubmittedOn != null)
                    hashCode = hashCode * 59 + this.SubmittedOn.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
