/*
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
 

namespace SpaceTradersDotNetSDK.Models
{
    /// <summary>
    /// ContractPayment
    /// </summary>
    [DataContract]
    public partial class ContractPayment :  IEquatable<ContractPayment>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ContractPayment" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ContractPayment() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ContractPayment" /> class.
        /// </summary>
        /// <param name="onAccepted">The amount of credits received up front for accepting the contract. (required).</param>
        /// <param name="onFulfilled">The amount of credits received when the contract is fulfilled. (required).</param>
        public ContractPayment(int onAccepted = default(int), int onFulfilled = default(int))
        {
            // to ensure "onAccepted" is required (not null)
            if (onAccepted == null)
            {
                throw new InvalidDataException("onAccepted is a required property for ContractPayment and cannot be null");
            }
            else
            {
                this.OnAccepted = onAccepted;
            }

            // to ensure "onFulfilled" is required (not null)
            if (onFulfilled == null)
            {
                throw new InvalidDataException("onFulfilled is a required property for ContractPayment and cannot be null");
            }
            else
            {
                this.OnFulfilled = onFulfilled;
            }

        }

        /// <summary>
        /// The amount of credits received up front for accepting the contract.
        /// </summary>
        /// <value>The amount of credits received up front for accepting the contract.</value>
        [DataMember(Name="onAccepted", EmitDefaultValue=true)]
        public int OnAccepted { get; set; }

        /// <summary>
        /// The amount of credits received when the contract is fulfilled.
        /// </summary>
        /// <value>The amount of credits received when the contract is fulfilled.</value>
        [DataMember(Name="onFulfilled", EmitDefaultValue=true)]
        public int OnFulfilled { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ContractPayment {\n");
            sb.Append("  OnAccepted: ").Append(OnAccepted).Append("\n");
            sb.Append("  OnFulfilled: ").Append(OnFulfilled).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ContractPayment);
        }

        /// <summary>
        /// Returns true if ContractPayment instances are equal
        /// </summary>
        /// <param name="input">Instance of ContractPayment to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ContractPayment input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.OnAccepted == input.OnAccepted ||
                    (this.OnAccepted != null &&
                    this.OnAccepted.Equals(input.OnAccepted))
                ) && 
                (
                    this.OnFulfilled == input.OnFulfilled ||
                    (this.OnFulfilled != null &&
                    this.OnFulfilled.Equals(input.OnFulfilled))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.OnAccepted != null)
                    hashCode = hashCode * 59 + this.OnAccepted.GetHashCode();
                if (this.OnFulfilled != null)
                    hashCode = hashCode * 59 + this.OnFulfilled.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
