/*
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
 

namespace SpaceTradersDotNetSDK.Models
{
    /// <summary>
    /// The current status of the ship
    /// </summary>
    /// <value>The current status of the ship</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum ShipNavStatus
    {
        /// <summary>
        /// Enum INTRANSIT for value: IN_TRANSIT
        /// </summary>
        [EnumMember(Value = "IN_TRANSIT")]
        INTRANSIT = 1,

        /// <summary>
        /// Enum INORBIT for value: IN_ORBIT
        /// </summary>
        [EnumMember(Value = "IN_ORBIT")]
        INORBIT = 2,

        /// <summary>
        /// Enum DOCKED for value: DOCKED
        /// </summary>
        [EnumMember(Value = "DOCKED")]
        DOCKED = 3

    }

}
