/*
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
 

namespace SpaceTradersDotNetSDK.Models
{
    /// <summary>
    /// The requirements for installation on a ship
    /// </summary>
    [DataContract]
    public partial class ShipRequirements :  IEquatable<ShipRequirements>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ShipRequirements" /> class.
        /// </summary>
        /// <param name="power">The amount of power required from the reactor..</param>
        /// <param name="crew">The number of crew required for operation..</param>
        /// <param name="slots">The number of module slots required for installation..</param>
        public ShipRequirements(int power = default(int), int crew = default(int), int slots = default(int))
        {
            this.Power = power;
            this.Crew = crew;
            this.Slots = slots;
        }

        /// <summary>
        /// The amount of power required from the reactor.
        /// </summary>
        /// <value>The amount of power required from the reactor.</value>
        [DataMember(Name="power", EmitDefaultValue=false)]
        public int Power { get; set; }

        /// <summary>
        /// The number of crew required for operation.
        /// </summary>
        /// <value>The number of crew required for operation.</value>
        [DataMember(Name="crew", EmitDefaultValue=false)]
        public int Crew { get; set; }

        /// <summary>
        /// The number of module slots required for installation.
        /// </summary>
        /// <value>The number of module slots required for installation.</value>
        [DataMember(Name="slots", EmitDefaultValue=false)]
        public int Slots { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ShipRequirements {\n");
            sb.Append("  Power: ").Append(Power).Append("\n");
            sb.Append("  Crew: ").Append(Crew).Append("\n");
            sb.Append("  Slots: ").Append(Slots).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ShipRequirements);
        }

        /// <summary>
        /// Returns true if ShipRequirements instances are equal
        /// </summary>
        /// <param name="input">Instance of ShipRequirements to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ShipRequirements input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Power == input.Power ||
                    (this.Power != null &&
                    this.Power.Equals(input.Power))
                ) && 
                (
                    this.Crew == input.Crew ||
                    (this.Crew != null &&
                    this.Crew.Equals(input.Crew))
                ) && 
                (
                    this.Slots == input.Slots ||
                    (this.Slots != null &&
                    this.Slots.Equals(input.Slots))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Power != null)
                    hashCode = hashCode * 59 + this.Power.GetHashCode();
                if (this.Crew != null)
                    hashCode = hashCode * 59 + this.Crew.GetHashCode();
                if (this.Slots != null)
                    hashCode = hashCode * 59 + this.Slots.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
