/*
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
 

namespace SpaceTradersDotNetSDK.Models
{
    /// <summary>
    /// A ship
    /// </summary>
    [DataContract]
    public partial class Ship :  IEquatable<Ship>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Ship" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Ship() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Ship" /> class.
        /// </summary>
        /// <param name="symbol">The globally unique identifier of the ship in the following format: &#x60;[AGENT_SYMBOL]_[HEX_ID]&#x60; (required).</param>
        /// <param name="registration">registration (required).</param>
        /// <param name="nav">nav (required).</param>
        /// <param name="crew">crew (required).</param>
        /// <param name="frame">frame (required).</param>
        /// <param name="reactor">reactor (required).</param>
        /// <param name="engine">engine (required).</param>
        /// <param name="modules">modules (required).</param>
        /// <param name="mounts">mounts (required).</param>
        /// <param name="cargo">cargo (required).</param>
        /// <param name="fuel">fuel (required).</param>
        public Ship(string symbol = default(string), ShipRegistration registration = default(ShipRegistration), ShipNav nav = default(ShipNav), ShipCrew crew = default(ShipCrew), ShipFrame frame = default(ShipFrame), ShipReactor reactor = default(ShipReactor), ShipEngine engine = default(ShipEngine), List<ShipModule> modules = default(List<ShipModule>), List<ShipMount> mounts = default(List<ShipMount>), ShipCargo cargo = default(ShipCargo), ShipFuel fuel = default(ShipFuel))
        {
            // to ensure "symbol" is required (not null)
            if (symbol == null)
            {
                throw new InvalidDataException("symbol is a required property for Ship and cannot be null");
            }
            else
            {
                this.Symbol = symbol;
            }

            // to ensure "registration" is required (not null)
            if (registration == null)
            {
                throw new InvalidDataException("registration is a required property for Ship and cannot be null");
            }
            else
            {
                this.Registration = registration;
            }

            // to ensure "nav" is required (not null)
            if (nav == null)
            {
                throw new InvalidDataException("nav is a required property for Ship and cannot be null");
            }
            else
            {
                this.Nav = nav;
            }

            // to ensure "crew" is required (not null)
            if (crew == null)
            {
                throw new InvalidDataException("crew is a required property for Ship and cannot be null");
            }
            else
            {
                this.Crew = crew;
            }

            // to ensure "frame" is required (not null)
            if (frame == null)
            {
                throw new InvalidDataException("frame is a required property for Ship and cannot be null");
            }
            else
            {
                this.Frame = frame;
            }

            // to ensure "reactor" is required (not null)
            if (reactor == null)
            {
                throw new InvalidDataException("reactor is a required property for Ship and cannot be null");
            }
            else
            {
                this.Reactor = reactor;
            }

            // to ensure "engine" is required (not null)
            if (engine == null)
            {
                throw new InvalidDataException("engine is a required property for Ship and cannot be null");
            }
            else
            {
                this.Engine = engine;
            }

            // to ensure "modules" is required (not null)
            if (modules == null)
            {
                throw new InvalidDataException("modules is a required property for Ship and cannot be null");
            }
            else
            {
                this.Modules = modules;
            }

            // to ensure "mounts" is required (not null)
            if (mounts == null)
            {
                throw new InvalidDataException("mounts is a required property for Ship and cannot be null");
            }
            else
            {
                this.Mounts = mounts;
            }

            // to ensure "cargo" is required (not null)
            if (cargo == null)
            {
                throw new InvalidDataException("cargo is a required property for Ship and cannot be null");
            }
            else
            {
                this.Cargo = cargo;
            }

            // to ensure "fuel" is required (not null)
            if (fuel == null)
            {
                throw new InvalidDataException("fuel is a required property for Ship and cannot be null");
            }
            else
            {
                this.Fuel = fuel;
            }

        }

        /// <summary>
        /// The globally unique identifier of the ship in the following format: &#x60;[AGENT_SYMBOL]_[HEX_ID]&#x60;
        /// </summary>
        /// <value>The globally unique identifier of the ship in the following format: &#x60;[AGENT_SYMBOL]_[HEX_ID]&#x60;</value>
        [DataMember(Name="symbol", EmitDefaultValue=true)]
        public string Symbol { get; set; }

        /// <summary>
        /// Gets or Sets Registration
        /// </summary>
        [DataMember(Name="registration", EmitDefaultValue=true)]
        public ShipRegistration Registration { get; set; }

        /// <summary>
        /// Gets or Sets Nav
        /// </summary>
        [DataMember(Name="nav", EmitDefaultValue=true)]
        public ShipNav Nav { get; set; }

        /// <summary>
        /// Gets or Sets Crew
        /// </summary>
        [DataMember(Name="crew", EmitDefaultValue=true)]
        public ShipCrew Crew { get; set; }

        /// <summary>
        /// Gets or Sets Frame
        /// </summary>
        [DataMember(Name="frame", EmitDefaultValue=true)]
        public ShipFrame Frame { get; set; }

        /// <summary>
        /// Gets or Sets Reactor
        /// </summary>
        [DataMember(Name="reactor", EmitDefaultValue=true)]
        public ShipReactor Reactor { get; set; }

        /// <summary>
        /// Gets or Sets Engine
        /// </summary>
        [DataMember(Name="engine", EmitDefaultValue=true)]
        public ShipEngine Engine { get; set; }

        /// <summary>
        /// Gets or Sets Modules
        /// </summary>
        [DataMember(Name="modules", EmitDefaultValue=true)]
        public List<ShipModule> Modules { get; set; }

        /// <summary>
        /// Gets or Sets Mounts
        /// </summary>
        [DataMember(Name="mounts", EmitDefaultValue=true)]
        public List<ShipMount> Mounts { get; set; }

        /// <summary>
        /// Gets or Sets Cargo
        /// </summary>
        [DataMember(Name="cargo", EmitDefaultValue=true)]
        public ShipCargo Cargo { get; set; }

        /// <summary>
        /// Gets or Sets Fuel
        /// </summary>
        [DataMember(Name="fuel", EmitDefaultValue=true)]
        public ShipFuel Fuel { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Ship {\n");
            sb.Append("  Symbol: ").Append(Symbol).Append("\n");
            sb.Append("  Registration: ").Append(Registration).Append("\n");
            sb.Append("  Nav: ").Append(Nav).Append("\n");
            sb.Append("  Crew: ").Append(Crew).Append("\n");
            sb.Append("  Frame: ").Append(Frame).Append("\n");
            sb.Append("  Reactor: ").Append(Reactor).Append("\n");
            sb.Append("  Engine: ").Append(Engine).Append("\n");
            sb.Append("  Modules: ").Append(Modules).Append("\n");
            sb.Append("  Mounts: ").Append(Mounts).Append("\n");
            sb.Append("  Cargo: ").Append(Cargo).Append("\n");
            sb.Append("  Fuel: ").Append(Fuel).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Ship);
        }

        /// <summary>
        /// Returns true if Ship instances are equal
        /// </summary>
        /// <param name="input">Instance of Ship to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Ship input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Symbol == input.Symbol ||
                    (this.Symbol != null &&
                    this.Symbol.Equals(input.Symbol))
                ) && 
                (
                    this.Registration == input.Registration ||
                    (this.Registration != null &&
                    this.Registration.Equals(input.Registration))
                ) && 
                (
                    this.Nav == input.Nav ||
                    (this.Nav != null &&
                    this.Nav.Equals(input.Nav))
                ) && 
                (
                    this.Crew == input.Crew ||
                    (this.Crew != null &&
                    this.Crew.Equals(input.Crew))
                ) && 
                (
                    this.Frame == input.Frame ||
                    (this.Frame != null &&
                    this.Frame.Equals(input.Frame))
                ) && 
                (
                    this.Reactor == input.Reactor ||
                    (this.Reactor != null &&
                    this.Reactor.Equals(input.Reactor))
                ) && 
                (
                    this.Engine == input.Engine ||
                    (this.Engine != null &&
                    this.Engine.Equals(input.Engine))
                ) && 
                (
                    this.Modules == input.Modules ||
                    this.Modules != null &&
                    input.Modules != null &&
                    this.Modules.SequenceEqual(input.Modules)
                ) && 
                (
                    this.Mounts == input.Mounts ||
                    this.Mounts != null &&
                    input.Mounts != null &&
                    this.Mounts.SequenceEqual(input.Mounts)
                ) && 
                (
                    this.Cargo == input.Cargo ||
                    (this.Cargo != null &&
                    this.Cargo.Equals(input.Cargo))
                ) && 
                (
                    this.Fuel == input.Fuel ||
                    (this.Fuel != null &&
                    this.Fuel.Equals(input.Fuel))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Symbol != null)
                    hashCode = hashCode * 59 + this.Symbol.GetHashCode();
                if (this.Registration != null)
                    hashCode = hashCode * 59 + this.Registration.GetHashCode();
                if (this.Nav != null)
                    hashCode = hashCode * 59 + this.Nav.GetHashCode();
                if (this.Crew != null)
                    hashCode = hashCode * 59 + this.Crew.GetHashCode();
                if (this.Frame != null)
                    hashCode = hashCode * 59 + this.Frame.GetHashCode();
                if (this.Reactor != null)
                    hashCode = hashCode * 59 + this.Reactor.GetHashCode();
                if (this.Engine != null)
                    hashCode = hashCode * 59 + this.Engine.GetHashCode();
                if (this.Modules != null)
                    hashCode = hashCode * 59 + this.Modules.GetHashCode();
                if (this.Mounts != null)
                    hashCode = hashCode * 59 + this.Mounts.GetHashCode();
                if (this.Cargo != null)
                    hashCode = hashCode * 59 + this.Cargo.GetHashCode();
                if (this.Fuel != null)
                    hashCode = hashCode * 59 + this.Fuel.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
